export const FONTS = {
  GilroyBlackItalic: 'Gilroy-BlackItalic',
  GilroyBold: 'Gilroy-Bold',
  GilroyBoldItalic: 'Gilroy-BoldItalic',
  GilroyExtraBold: 'Gilroy-ExtraBold',
  GilroyExtraBoldItalic: 'Gilroy-ExtraBoldItalic',
  GilroyHeavy: 'Gilroy-Heavy',
  GilroyHeavyItalic: 'Gilroy-HeavyItalic',
  GilroyLight: 'Gilroy-Light',
  GilroyLightItalic: 'Gilroy-LightItalic',
  GilroyMedium: 'Gilroy-Medium',
  GilroyMediumItalic: 'Gilroy-MediumItalic',
  GilroyRegular: 'Gilroy-Regular',
  GilroyRegularItalic: 'Gilroy-RegularItalic',
  GilroySemiBold: 'Gilroy-SemiBold',
  GilroySemiBoldItalic: 'Gilroy-SemiBoldItalic',
  GilroyThin: 'Gilroy-Thin',
  GilroyThinItalic: 'Gilroy-ThinItalic',
  GilroyUltraLight: 'Gilroy-UltraLight',
  GilroyUltraLightItalic: 'Gilroy-UltraLightItalic',
};
