export const MAIN_NAV_STRINGS = {
  SPLASH: 'SPLASH',
  INTRO: 'INTRO',
  AUTHSTACK: 'AUTHSTACK',
  MAINSTACK: 'MAINSTACK',
  CART_SCREEN: 'CART_SCREEN',
  PICK_COLLECT_SCREEN: 'PICK_COLLECT_SCREEN',
  CHECKOUT: 'CHECKOUT',
  ORDER_DETAILS: 'ORDER_DETAILS',
  ORDER_SUCCESS: 'ORDER_SUCCESS',
  ORDER_FAILURE: 'ORDER_FAILURE',
  ADDRESS_LIST: 'ADDRESS_LIST',
  ADD_ADDRESS_MAP: 'ADD_ADDRESS_MAP',
  ADD_ADDRESS: 'ADD_ADDRESS',
  FAQ: 'FAQ',
  PAYMENT: 'PAYMENT',
};

export const AUTH_STACK_STRINGS = {
  SIGNUP: 'SIGNUP',
  LOGIN: 'LOGIN',
};

export const MAIN_STACK_STRINGS = {
  HOME: 'HomeScreen',
  SERVICE_OVERVIEW: 'ServiceOverview',
  CART: 'CartScreen',
  PICK_COLLECT: 'PICK_COLLECT',
  PROFILE: 'PriceScreen',
  ORDER_SCREEN: 'OrderScreen',
  ACCOUNT: 'AccountScreen',
};
